[features]
seeds = false
skip-lint = false

[programs.localnet]
token_staking = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "/users/lk/Downloads/test-new-loveleet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
[toolchain]
anchor_version = "0.28.0"